---
EnableDefaultLinters: true
linters:
  AllowedScriptType:
    enabled: true
    allowed_types:
      - text/javascript
      - application/javascript
  ClosingErbTagIndent:
    enabled: true
  FinalNewline:
    enabled: true
    present: true
  NoJavascriptTagHelper:
    enabled: true
  ParserErrors:
    enabled: true
  RightTrim:
    enabled: true
    enforced_style: '-'
  SelfClosingTag:
    enabled: true
    enforced_style: always
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/LineLength:
        Max: 100
        Exclude:
          - 'app/views/**/*.erb'
  SpaceAroundErbTag:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
  TrailingWhitespace:
    enabled: true
    exclude:
      - app/views/mailers/**/*
exclude:
  - node_modules/**/*
  - vendor/**/*
  - public/**/*
  - tmp/**/*
  - log/**/*
