default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: adorn_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: adorn_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
    database: adorn_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: adorn_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: adorn_production_cable
    migrations_paths: db/cable_migrate
